apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-webhook
  name: auth-webhook
  namespace: learn
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: auth-webhook
  type: ClusterIP
