apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-stack
  name: backend-stack
  namespace: learn 
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend-stack
  type: ClusterIP
