---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: graphiql
  name: graphiql
  namespace: learn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: graphiql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: graphiql
    spec:
      containers:
      - image: IMG_PATH:latest
        imagePullPolicy: Always
        name: graphiql
        env:
        - name: GRAPHQL_ENDPOINT
          value: https://hasura.io/learn/graphql
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "32Mi"
            cpu: "1m"
          limits:
            memory: "256Mi"
            cpu: "100m"

