apiVersion: v1
kind: Service
metadata:
  labels:
    app: svelte-apollo
  name: svelte-apollo
  namespace: learn
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: svelte-apollo
  type: ClusterIP