apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasura-backend
  name: hasura-backend
  namespace: learn 
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hasura-backend
  type: ClusterIP
