apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasura-auth-slack
  name: hasura-auth-slack
  namespace: learn 
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hasura-auth-slack
  type: ClusterIP