apiVersion: v1
kind: Service
metadata:
  labels:
    app: flutter-graphql
  name: flutter-graphql
  namespace: learn
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: flutter-graphql
  type: ClusterIP