apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: react-rxdb
  namespace: learn 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-rxdb
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 200Mi