apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-rxdb
  name: react-rxdb
  namespace: learn
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: react-rxdb
  type: ClusterIP