apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasura-backend-es
  name: hasura-backend-es
  namespace: learn 
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hasura-backend-es
  type: ClusterIP