apiVersion: v1
kind: Service
metadata:
  labels:
    app: remix-fullstack-firebase
  name: remix-fullstack-firebase
  namespace: learn
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: remix-fullstack-firebase
  type: ClusterIP