apiVersion: v1
kind: Service
metadata:
  labels:
    app: asp-dotnet-mvc
  name: asp-dotnet-mvc
  namespace: learn
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: asp-dotnet-mvc
  type: ClusterIP