apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-apollo-hooks
  name: react-apollo-hooks
  namespace: learn
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: react-apollo-hooks
  type: ClusterIP