apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextjs-fullstack-serverless
  name: nextjs-fullstack-serverless
  namespace: learn
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nextjs-fullstack-serverless
  type: ClusterIP