apiVersion: v1
kind: Service
metadata:
  labels:
    app: intro-graphql-es
  name: intro-graphql-es
  namespace: learn
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: intro-graphql-es
  type: ClusterIP