apiVersion: v1
kind: Service
metadata:
  labels:
    app: unity
  name: unity
  namespace: learn
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: unity
  type: ClusterIP