apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-jwt-server
  name: auth-jwt-server
  namespace: learn
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: auth-jwt-server
  type: ClusterIP