apiVersion: v1
kind: Service
metadata:
  labels:
    app: database-postgresql
  name: database-postgresql
  namespace: learn
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: database-postgresql
  type: ClusterIP