apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: database-yugabyte
  namespace: learn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: database-yugabyte
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 200Mi
